import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Navbar } from "@/components/navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div 
          className="flex flex-col min-h-screen bg-background text-foreground"
          style={{ 
            fontFamily: 'Helvetica, Arial, sans-serif'
          }}
        >
          {/* Navigation Bar */}
          <Navbar />

          {/* Main content */}
          {children}

          {/* Footer at bottom */}
          {/* <footer 
            className="text-center py-8 text-sm text-muted-foreground"
          >
            © 2025 Arien Aviation. All rights reserved.
          </footer> */}
        </div>
      </body>
    </html>
  );
}
